#! /bin/bash

for BASHES in $(ls ~/.aliases/bash-*)
do
    [ -f "$BASHES" ] && source "$BASHES"
done
#. /usr/share/.asdf/asdf.sh
#. /usr/share/.asdf/completions/asdf.bash
export PATH="${ASDF_DATA_DIR:-$HOME/.asdf}/shims:$PATH"
eval "$(gh completion -s bash)"
