#! /bin/bash
#

# create an alias to search how to do somthing on terminal, without leave the terminal
duckit () { w3m duckduckgo.com/?q="$@"; }

# extract any archive format
# orrsella/dotfiles on github
extract() {
    if [ -f $1 ] ; then
        case $1 in
            *.tar.bz2)  tar xvjf $1      ;;
            *.tar.gz)   tar xvzf $1      ;;
            *.bz2)      bunzip2 $1      ;;
            *.rar)      unrar xv $1      ;;
            *.gz)       gunzip $1       ;;
            *.tar)      tar xvf $1       ;;
            *.tbz2)     tar xvjf $1      ;;
            *.tgz)      tar xvzf $1      ;;
            *.zip)      unzip $1        ;;
            *.jar)      unzip $1        ;;
            *.war)      unzip $1        ;;
            *.Z)        uncompress $1   ;;
            *)          echo "'$1' cannot be extracted via extract()" ;;
        esac
    else
        echo "'$1' is not a valid file"
    fi
}

psgrep() {
  if [ ! -z $1 ] ; then
      echo "Grepping for processes matching $1..."
      ps aux | grep $1 | grep -v grep
    else
        echo "!! Need name to grep for"
      fi
  }

# Kills any process that matches a regexp passed to it
killit() {
    ps aux | grep -v "grep" | grep "$@" | awk '{print $2}' | xargs sudo kill
}

mergeit() {
    pr -m -t $1 $2 > $3
}

# configure author of git repo
marinoit() {
    git config user.name Marinofull
    git config user.email Marinofull@users.noreply.github.com
}

# configure keyboard free of emmac's pinky and run tmux
run-nice-keyboard() {
    setxkbmap -option ctrl:swapcaps
    tmux
}

# copy to graphic clipboard
copy() {
    xclip -selection clipboard $1
}
