#! /bin/bash
#

# create an alias to search how to do somthing on terminal, without leave the terminal
duckit () { w3m duckduckgo.com/?q="$@"; }

# extract any archive format
# orrsella/dotfiles on github
extract() {
    if [ -f $1 ] ; then
        case $1 in
            *.tar.bz2)  tar xvjf $1      ;;
            *.tar.gz)   tar xvzf $1      ;;
            *.tar.xz)   tar -Jxvf $1     ;;
            *.bz2)      bunzip2 -k $1      ;;
            *.rar)      unrar x $1      ;;
            *.gz)       gunzip -k $1       ;;
            *.tar)      tar xvf $1       ;;
            *.tbz2)     tar xvjf $1      ;;
            *.tgz)      tar xvzf $1      ;;
            *.zip)      unzip $1 -d ${1%$".zip"} ;;
            *.jar)      unzip $1        ;;
            *.war)      unzip $1        ;;
            *.7z)       7z e $1        ;;
            *.Z)        uncompress $1   ;;
            *)          echo "'$1' cannot be extracted via extract()" ;;
        esac
    else
        echo "'$1' is not a valid file"
    fi
}

psgrep() {
  if [ ! -z $1 ] ; then
      echo "Grepping for processes matching $1..."
      ps aux | grep $1 | grep -v grep
    else
        echo "!! Need name to grep for"
      fi
  }

# Kills any process that matches a regexp passed to it
killit() {
    ps aux | grep -v "grep" | grep "$@" | awk '{print $2}' | xargs sudo kill
}

mergeit() {
    pr -m -t $1 $2 > $3
}

# configure author of git repo
marinoit() {
    git config user.name Marinofull
    git config user.email Marinofull@users.noreply.github.com
}

# configure keyboard free of emmac's pinky and run tmux
run-nice-keyboard() {
    setxkbmap -option ctrl:swapcaps
    tmux
}

run-nice-keyboard-console() {
# You have to be root to remap the console keyboard.
if [ "$(id -u)" != "0" ]; then
    echo "This script is not running as root so"
    echo "the console CapsLock cannot be remapped."
    echo "Perhaps you forgot to run this under sudo."
    echo "Note that this problem does not effect X."
    echo "This only effects the consoles running on"
    echo "Alt-f1 through Alt-f6."
    exit 2
fi

# Remap the CapsLock key to a Control key for the console.
(dumpkeys | grep keymaps; echo "keycode 58 = Control") | loadkeys

}

# copy to graphic clipboard
copy() {
    xclip -selection clipboard $1
}

# video clipper, requires avconv package
# usage:
# $ corte input.ext daqui paca output.ext
# daqui formmat: hh:mm:ss
# paca formmat: hh:mm:ss
corte() {
    avconv -i $1 -vcodec copy -acodec copy -ss $2 -t $3 $4
}

# get video height and width measures
ff-measures() {
    ffprobe -v quiet  -show_streams $1 | grep 'coded'
}

runflux() {
    xflux -l 0 -g 0 -k 3400 # flux
}
