#! /bin/bash
#

#set a alias to vim on spell mode, the language must be passed as a parameter [pt, en]
#vimspell () { vim -c 'set spell spelllang=pt,en'; }
alias vimspell="vim -c 'set spell spelllang=pt,en'"
alias tinker="rlwrap php artisan tinker"
alias grep='grep --color=auto'
alias dotfile="cd $HOME/.dotfiles"
alias gopassrepo="cd $HOME/.local/share/gopass/stores/root"
